[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x656a43f6da4fbbad0cbc36a176021e310f58da1f5f56e6738509dd722ff40db9'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
